server:
  port: 10077
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: localhost
    database: 0
    port: 6379
    password:

    jedis:
      pool:
        max-wait: -1ms
        min-idle: 0
        max-idle: 8
        max-active: 8
    timeout: 3000ms
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9200
    mongodb:
      host: localhost
      port: 27017
      database: mall-port
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /shop
    username: lf
    password: lf123
    publisher-confirms: true

redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 120
  redis:
    key:
      prefix:
        authCode: "portal:authCode:"
      expire:
        authCode: 120
mybatis:
  mapper-locations: classpath:mapper/**/**.xml


jwt:
  tokenHeader: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: Bearer